### PR TITLE
Migrate to APIs.guru's URLs

### PR DESCRIPTION
**Pull request by IvanGoncharov**

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
@bobby-brennan Can you please do the same changes in Medium copy.

**Comment by rbren** [comment]
Thanks! Everything on Medium.com is uploaded to their CDN, it's not a live image

**Comment by IvanGoncharov** [comment]
@bobby-brennan I mean link to `list.json` and Instagram spec.

**Comment by rbren** [comment]
Ahh gotcha. Done!

Bobby Brennan
bobby.brennan@gmail.com

**Pull request merged**
